name = "hugocast"
license = "MIT"
licenselink = ""
description = "A podcasting tool based on hugo"
homepage = "https://github.com/tourcoder/hugocast"
tags = ["podcast", "hugo", "hugocast"]
features = ["podcast"]
min_version = "0.1"

[author]
  name = "Bin Hua"
  homepage = "https://github.com/tourcoder/hugocast"
  repo = "https://github.com/tourcoder/hugocast.git"
